### ISSUE TITLE
Add exception handler for "Invalid amount" for /send & /swap

### ISSUE THREAD

**Issue by HenryYoung42** [project-ecc/ecchat#1]
Reported by N00BonICE:

/send 0.00000001 caused a crash:

Traceback (most recent call last):
  File "ecchat.py", line 1230, in <module>
    main()
  File "ecchat.py", line 1222, in main
    app.run()
  File "ecchat.py", line 1173, in run
    self.loop.run()
  File "/home/N00BonICE/.local/lib/python3.6/site-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "/home/N00BonICE/.local/lib/python3.6/site-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "/home/N00BonICE/eccoin/ecchat-master/zmqeventloop.py", line 174, in run
    self._loop()
  File "/home/N00BonICE/eccoin/ecchat-master/zmqeventloop.py", line 236, in _loop
    self._queue_callbacks[queue](self._queue_callbacki[queue])          # Call for zmq queue
  File "ecchat.py", line 1084, in zmqHandler
    self.complete_send(data['addr'])
  File "ecchat.py", line 304, in complete_send
    self.txid = coins[self.send_index].send_to_address(address, str(self.send_amount), "ecchat")
  File "/home/N00BonICE/eccoin/ecchat-master/cryptonode.py", line 246, in send_to_address
    return self.proxy.sendtoaddress(address, amount, comment)
  File "/home/N00BonICE/eccoin/ecchat-master/slickrpc/rpc.py", line 75, in call
    raise RpcException(resp['error'], method, params)
slickrpc.exc.RpcTypeError: sendtoaddress: Invalid amount (code -3)

**Comment by HenryYoung42** [comment]
Caused by trying to send an amount with 8 decimal places. ECC only allows for 6 decimal places.

Fix will be to trap this error with an exception handler and output a suitable message to the user.

**Comment by HenryYoung42** [comment]
Fixed - example output:

[22:48:03]    bob > /send 0.00000001
[22:48:07] ecchat | Invalid amount
